# Generated by Django 6.0 on 2025-12-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "prembly_api_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "conversation_state",
                    models.CharField(
                        choices=[
                            ("NEW_USER", "New User"),
                            ("AWAITING_AUTH_KEY", "Awaiting API Key"),
                            ("AUTHENTICATED", "Authenticated"),
                            (
                                "AWAITING_VERIFICATION_TYPE",
                                "Awaiting Verification Type",
                            ),
                            ("AWAITING_PHONE_INPUT", "Awaiting Phone Number Input"),
                        ],
                        default="NEW_USER",
                        max_length=50,
                    ),
                ),
                ("last_interaction", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
