# Generated by Django 6.0 on 2025-12-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_verification_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
