# Generated by Django 6.0 on 2025-12-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_userprofile_last_verification_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="conversation_state",
            field=models.CharField(
                choices=[
                    ("NEW_USER", "New User"),
                    ("AWAITING_AUTH_KEY", "Awaiting API Key"),
                    ("AUTHENTICATED", "Authenticated"),
                    ("AWAITING_VERIFICATION_TYPE", "Awaiting Verification Type"),
                    ("AWAITING_PHONE_INPUT", "Awaiting Phone Number Input"),
                    ("AWAITING_BVN_INPUT", "Awaiting BVN Input"),
                    ("AWAITING_NIN_INPUT", "Awaiting NIN Input"),
                ],
                default="NEW_USER",
                max_length=50,
            ),
        ),
    ]
